site_name: LayeredCraft.EntityFrameworkCore.DynamoDb
docs_dir: docs
nav:
  - Home: index.md
  - Configuration: configuration.md
  - Querying:
      - Operators: operators.md
      - Pagination: pagination.md
      - Projections: projections.md
  - Diagnostics: diagnostics.md
  - Limitations: limitations.md
