services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    ports:
      - "8000:8000"
    networks:
      - dynamodb-network

  dynamodb-seeder:
    image: amazon/aws-cli:latest
    container_name: dynamodb-seeder
    volumes:
      - ./scripts:/scripts
      - ./data:/data
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=us-east-1
    networks:
      - dynamodb-network
    depends_on:
      - dynamodb-local
    entrypoint: [ "/bin/sh", "/scripts/seed-database.sh" ]
    restart: "no"

networks:
  dynamodb-network:
    driver: bridge
